#pragma once

#include "For_Kadath/Array/headcpp.hpp"
#include "For_Kadath/Array/array.hpp"
#include "For_Kadath/Base_tensor/base_tensor.hpp"
#include "For_Kadath/Base_spectral/base_spectral.hpp"
#include "For_Kadath/Matrice/matrice.hpp"
#include "For_Kadath/Utilities/name_tools.hpp"
#include "For_Kadath/Ope_eq/ope_eq.hpp"
#include "For_Kadath/Param/param.hpp"
#include "For_Kadath/Array/point.hpp"
#include "For_Kadath/Scalar/scalar.hpp"
#include "For_Kadath/Tensor/tensor.hpp"
#include "For_Kadath/Tensor/vector.hpp"
#include "For_Kadath/Tensor/metric_tensor.hpp"
#include "For_Kadath/Metric/metric.hpp"
#include "For_Kadath/Term_eq/term_eq.hpp"
#include "For_Kadath/System_of_eqs/system_of_eqs.hpp"

#include "For_Kadath/Space/bin_ns_nosym.hpp"
