function(_celephais_wrapper_show _compiler _out)
    set(_show "")
    if(_compiler)
        foreach(_flag IN ITEMS --showme:command --showme:link -show)
            execute_process(
                COMMAND "${_compiler}" ${_flag}
                RESULT_VARIABLE _res
                OUTPUT_VARIABLE _stdout
                ERROR_VARIABLE _stderr
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_STRIP_TRAILING_WHITESPACE)
            if(_res EQUAL 0 AND NOT _stdout STREQUAL "")
                set(_show "${_stdout}")
                break()
            endif()
        endforeach()
    endif()
    set(${_out} "${_show}" PARENT_SCOPE)
endfunction()

function(celephais_print_stack_report)
    _celephais_wrapper_show("${CMAKE_CXX_COMPILER}" _CELEPHAIS_MPI_CXX_SHOW)
    _celephais_wrapper_show("${CMAKE_Fortran_COMPILER}" _CELEPHAIS_MPI_FORTRAN_SHOW)

    set(CELEPHAIS_STACK_TARGET_CLASS "${CELEPHAIS_TARGET_CLASS}" CACHE STRING "Celephais target class" FORCE)
    set(CELEPHAIS_STACK_C_COMPILER "${CMAKE_C_COMPILER}" CACHE STRING "Celephais C compiler" FORCE)
    set(CELEPHAIS_STACK_CXX_COMPILER "${CMAKE_CXX_COMPILER}" CACHE STRING "Celephais C++ compiler" FORCE)
    set(CELEPHAIS_STACK_Fortran_COMPILER "${CMAKE_Fortran_COMPILER}" CACHE STRING "Celephais Fortran compiler" FORCE)
    set(CELEPHAIS_STACK_MPI_CXX_SHOW "${_CELEPHAIS_MPI_CXX_SHOW}" CACHE STRING "Celephais MPI C++ wrapper report" FORCE)
    set(CELEPHAIS_STACK_MPI_Fortran_SHOW "${_CELEPHAIS_MPI_FORTRAN_SHOW}" CACHE STRING "Celephais MPI Fortran wrapper report" FORCE)
    if(CELEPHAIS_ENABLE_FFTW_ORACLE)
        set(CELEPHAIS_STACK_FFTW "${FFTW_LIBRARIES}" CACHE STRING "Celephais test-oracle FFTW libraries" FORCE)
    else()
        set(CELEPHAIS_STACK_FFTW "disabled" CACHE STRING "Celephais test-oracle FFTW libraries" FORCE)
    endif()
    set(CELEPHAIS_STACK_BLAS "${BLAS_LIBRARIES}" CACHE STRING "Celephais BLAS libraries" FORCE)
    set(CELEPHAIS_STACK_LAPACK "${LAPACK_LIBRARIES}" CACHE STRING "Celephais LAPACK libraries" FORCE)
    set(CELEPHAIS_STACK_SCALAPACK "${SCALAPACK_LIBRARIES}" CACHE STRING "Celephais ScaLAPACK libraries" FORCE)
    set(CELEPHAIS_STACK_MUMPS_PROVIDER "${MUMPS_PROVIDER}" CACHE STRING "Celephais MUMPS provider" FORCE)
    set(CELEPHAIS_STACK_MUMPS_INCLUDE "${MUMPS_INCLUDE_DIRS}" CACHE STRING "Celephais MUMPS include dirs" FORCE)
    set(CELEPHAIS_STACK_MUMPS_LINK "${MUMPS_LINK_LIBRARIES}" CACHE STRING "Celephais MUMPS link libraries" FORCE)

    message(STATUS "Celephais stack report")
    message(STATUS "  target class: ${CELEPHAIS_TARGET_CLASS}")
    message(STATUS "  C compiler: ${CMAKE_C_COMPILER}")
    message(STATUS "  CXX compiler: ${CMAKE_CXX_COMPILER}")
    message(STATUS "  Fortran compiler: ${CMAKE_Fortran_COMPILER}")
    if(_CELEPHAIS_MPI_CXX_SHOW)
        message(STATUS "  MPI CXX wrapper: ${_CELEPHAIS_MPI_CXX_SHOW}")
    endif()
    if(_CELEPHAIS_MPI_FORTRAN_SHOW)
        message(STATUS "  MPI Fortran wrapper: ${_CELEPHAIS_MPI_FORTRAN_SHOW}")
    endif()
    message(STATUS "  FFTW test oracle: ${CELEPHAIS_STACK_FFTW}")
    message(STATUS "  BLAS: ${BLAS_LIBRARIES}")
    message(STATUS "  LAPACK: ${LAPACK_LIBRARIES}")
    message(STATUS "  ScaLAPACK: ${SCALAPACK_LIBRARIES}")
    message(STATUS "  MUMPS provider: ${MUMPS_PROVIDER}")
    message(STATUS "  MUMPS include: ${MUMPS_INCLUDE_DIRS}")
    message(STATUS "  MUMPS link: ${MUMPS_LINK_LIBRARIES}")
endfunction()
