# Find FFTW and expose FFTW::FFTW.
#
# Accepts both the historical Kadath cache names (`FFTW_INCLUDES`, `FFTW_LIB`)
# and common CMake/toolchain names (`FFTW_INCLUDE_DIRS`, `FFTW_LIBRARIES`,
# `FFTW_INCLUDE_DIR`, `FFTW_LIBRARY`).

if(NOT FFTW_ROOT AND DEFINED ENV{FFTWDIR})
    set(FFTW_ROOT "$ENV{FFTWDIR}")
endif()
if(NOT FFTW_ROOT AND DEFINED ENV{FFTW_ROOT})
    set(FFTW_ROOT "$ENV{FFTW_ROOT}")
endif()
if(NOT FFTW_ROOT AND DEFINED ENV{FFTW_HOME})
    set(FFTW_ROOT "$ENV{FFTW_HOME}")
endif()

find_package(PkgConfig QUIET)
if(PKG_CONFIG_FOUND AND NOT FFTW_ROOT)
    pkg_check_modules(PKG_FFTW QUIET fftw3)
endif()

if(FFTW_INCLUDE_DIRS AND NOT FFTW_INCLUDES)
    set(FFTW_INCLUDES "${FFTW_INCLUDE_DIRS}")
elseif(FFTW_INCLUDE_DIR AND NOT FFTW_INCLUDES)
    set(FFTW_INCLUDES "${FFTW_INCLUDE_DIR}")
endif()

if(FFTW_LIBRARIES AND NOT FFTW_LIB)
    list(GET FFTW_LIBRARIES 0 FFTW_LIB)
elseif(FFTW_LIBRARY AND NOT FFTW_LIB)
    set(FFTW_LIB "${FFTW_LIBRARY}")
endif()

set(_FFTW_SUFFIXES lib lib64 lib/x86_64-linux-gnu)
set(_FFTW_HINT_LIB_DIRS ${PKG_FFTW_LIBRARY_DIRS})
set(_FFTW_HINT_INCLUDE_DIRS ${PKG_FFTW_INCLUDE_DIRS})
if(FFTW_ROOT)
    list(APPEND _FFTW_HINT_LIB_DIRS "${FFTW_ROOT}")
    list(APPEND _FFTW_HINT_INCLUDE_DIRS "${FFTW_ROOT}")
endif()

set(_FFTW_SUFFIXES_SAVE ${CMAKE_FIND_LIBRARY_SUFFIXES})
if(FFTW_USE_STATIC_LIBS)
    set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_STATIC_LIBRARY_SUFFIX})
elseif(CMAKE_SHARED_LIBRARY_SUFFIX)
    set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_SHARED_LIBRARY_SUFFIX})
endif()

find_library(FFTW_LIB
    NAMES fftw3
    HINTS ${_FFTW_HINT_LIB_DIRS}
    PATH_SUFFIXES ${_FFTW_SUFFIXES}
)
find_library(FFTW_THREADS_LIB
    NAMES fftw3_threads
    HINTS ${_FFTW_HINT_LIB_DIRS}
    PATH_SUFFIXES ${_FFTW_SUFFIXES}
)
find_library(FFTWF_LIB
    NAMES fftw3f
    HINTS ${_FFTW_HINT_LIB_DIRS}
    PATH_SUFFIXES ${_FFTW_SUFFIXES}
)
find_library(FFTWF_THREADS_LIB
    NAMES fftw3f_threads
    HINTS ${_FFTW_HINT_LIB_DIRS}
    PATH_SUFFIXES ${_FFTW_SUFFIXES}
)
find_library(FFTWL_LIB
    NAMES fftw3l
    HINTS ${_FFTW_HINT_LIB_DIRS}
    PATH_SUFFIXES ${_FFTW_SUFFIXES}
)
find_library(FFTWL_THREADS_LIB
    NAMES fftw3l_threads
    HINTS ${_FFTW_HINT_LIB_DIRS}
    PATH_SUFFIXES ${_FFTW_SUFFIXES}
)

set(CMAKE_FIND_LIBRARY_SUFFIXES ${_FFTW_SUFFIXES_SAVE})

find_path(FFTW_INCLUDES
    NAMES fftw3.h
    HINTS ${_FFTW_HINT_INCLUDE_DIRS}
    PATH_SUFFIXES include
)

if(NOT FFTW_LIBRARIES)
    set(FFTW_LIBRARIES "${FFTW_LIB}")
endif()
if(NOT FFTW_INCLUDE_DIRS)
    set(FFTW_INCLUDE_DIRS "${FFTW_INCLUDES}")
endif()

set(_FFTW_BROKEN_LIBRARIES)
foreach(_fftw_lib IN LISTS FFTW_LIBRARIES)
    if(IS_ABSOLUTE "${_fftw_lib}" AND NOT EXISTS "${_fftw_lib}")
        list(APPEND _FFTW_BROKEN_LIBRARIES "${_fftw_lib}")
    endif()
endforeach()
if(_FFTW_BROKEN_LIBRARIES)
    set(FFTW_LIBRARIES FFTW_LIBRARIES-NOTFOUND)
    set(FFTW_LIB FFTW_LIB-NOTFOUND)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FFTW
    REQUIRED_VARS FFTW_INCLUDES FFTW_LIBRARIES
    FAIL_MESSAGE "Could not find FFTW. Set FFTW_ROOT/FFTW_HOME/FFTWDIR. Broken libraries: ${_FFTW_BROKEN_LIBRARIES}"
)

if(FFTW_FOUND AND NOT TARGET FFTW::FFTW)
    add_library(FFTW::FFTW INTERFACE IMPORTED)
    target_include_directories(FFTW::FFTW INTERFACE "${FFTW_INCLUDES}")
    target_link_libraries(FFTW::FFTW INTERFACE ${FFTW_LIBRARIES})
endif()

mark_as_advanced(
    FFTW_INCLUDES
    FFTW_INCLUDE_DIRS
    FFTW_LIBRARIES
    FFTW_LIB
    FFTW_THREADS_LIB
    FFTWF_LIB
    FFTWF_THREADS_LIB
    FFTWL_LIB
    FFTWL_THREADS_LIB
)
